import * as configs from './config.js';

// Setup
document.title = configs.SITE_CONFIGS.title
setup();


// Functions
function setup(){
    // Site Configs
    for (const [key, value] of Object.entries(configs.SITE_CONFIGS)) {
        setPageText(key, value);
    }

    // Header Navigation
    for (const [key, value] of Object.entries(configs.HEADER_NAV)) {
        setPageText(key, value);
    }

    // Import and Display Photos from linked Google Drive Folder
    loadPhotos();
};

function setPageText(elementPlaceholderName, input){
    const allElements = document.getElementsByClassName(elementPlaceholderName.toString());
    for (const element of allElements){
        element.innerText = input;
    }
}

async function loadPhotos() {
	const galleryContainer = document.getElementById('image-gallery');

	try {
		// Fetch the gallery manifest generated by your GitHub Action build
		const response = await fetch('./assets/gallery.json');

		if (!response.ok) {
			throw new Error(`HTTP error! Status: ${response.status}`);
		}

		const photos = await response.json();

		// If no photos were returned
		if (photos.length === 0) {
			galleryContainer.innerHTML = '<p>No images found in the gallery.</p>';
			return;
		}

		// Clear any loading text/placeholders
		galleryContainer.innerHTML = '';

		// Loop through each image object and build the <img> tags
		photos.forEach(photo => {
			const img = document.createElement('img');
			img.src = photo.url.startsWith('./') ? photo.url : `./${photo.url}`;
			img.alt = photo.name;
			img.loading = 'lazy';

			galleryContainer.appendChild(img);
		});

	} catch (error) {
		console.error('Error loading gallery:', error);
		galleryContainer.innerHTML = '<p>Unable to load images at this time.</p>';
	}
}
